name: SampleStaticLibraryC
sln_path: Project/windows/SampleStaticLibraryC.sln
dependencies:
  - masahikotsujita/SampleStaticLibraryA
artifacts:
  include_headers:
    - Include/*
  link_libraries:
    - Dist/SampleStaticLibraryC_${PLATFORM}_${CONFIGURATION}.lib
