name: SampleStaticLibraryC
sln_path: Project/windows/SampleStaticLibraryC.sln
dependencies:
  - masahikotsujita/SampleStaticLibraryA
artifacts:
  - src: Include/*
    dst: ${ARTIFACTS_ROOT}/include/
  - src: Dist/*
    dst: ${ARTIFACTS_ROOT}/lib/

