name: SampleStaticLibraryC
sln_path: Project/windows/SampleStaticLibraryC.sln
dependencies:
  - project: masahikotsujita/SampleStaticLibraryA
    version: ^1.0.0
artifacts:
  include_headers:
    - Include/*
  link_libraries:
    - Dist/SampleStaticLibraryC_${PLATFORM}_${CONFIGURATION}.lib
